[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.normal]
family = "Input Nerd Font"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[window]
opacity = 0.9
